services:
  redis:
    image: redis:8-alpine
    container_name: cvsentry-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./Redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./Redis/users.acl:/usr/local/etc/redis/users.acl:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - ./Redis/.env
    healthcheck:
      test: [ "CMD", "redis-cli", "-u", "redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@localhost:6379", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cvsentry-net

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: cvsentry-app
    network_mode: "host"
    environment:
      PYTHONPATH: /app/app
      QDRANT_URL: http://localhost:6335
      DJANGO_URL: http://localhost:8000
      CLOUD_SRS_WHIP_URL: http://localhost:1985/rtc/v1/publish/
      NVIDIA_VISIBLE_DEVICES: all
    restart: unless-stopped
    env_file:
      - ./app/.env

  qdrant:
    image: qdrant/qdrant:latest
    container_name: cvsentry-qdrant
    restart: unless-stopped
    ports:
      - "6335:6333"
      - "6334:6334"
    volumes:
      - qdrant_local_data:/qdrant/storage
    networks:
      - cvsentry-net

volumes:
  redis_data:
  qdrant_local_data:

networks:
  cvsentry-net:
    name: cvsentry-net
