#!/usr/bin/env bash
# =============================================================================
# CVSentry Redis — Setup Script
# Reads credentials from .env and generates the users.acl file, then starts
# (or restarts) the Redis container via Docker Compose.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
ACL_FILE="${SCRIPT_DIR}/users.acl"

# ---------------------------------------------------------------------------
# 1. Verify .env exists
# ---------------------------------------------------------------------------
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "[ERROR] .env file not found at ${ENV_FILE}"
  echo "        Copy .env.example to .env and fill in your credentials."
  exit 1
fi

# ---------------------------------------------------------------------------
# 2. Load .env (ignore comments and blank lines)
# ---------------------------------------------------------------------------
set -o allexport
# shellcheck disable=SC1090
source <(grep -v '^\s*#' "${ENV_FILE}" | grep -v '^\s*$')
set +o allexport

# ---------------------------------------------------------------------------
# 3. Validate required variables
# ---------------------------------------------------------------------------
: "${REDIS_USERNAME:?REDIS_USERNAME must be set in .env}"
: "${REDIS_PASSWORD:?REDIS_PASSWORD must be set in .env}"

# ---------------------------------------------------------------------------
# 4. Generate users.acl
# ---------------------------------------------------------------------------
echo "[INFO] Generating ${ACL_FILE} ..."
cat > "${ACL_FILE}" << EOF
# Redis ACL — auto-generated by setup.sh — do not edit manually
# Re-run ./setup.sh to regenerate after changing .env

# Disable the built-in 'default' user (no unauthenticated access)
user default off nopass nocommands nokeys

# CVSentry application user — full access
user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* &* +@all
EOF

echo "[INFO] users.acl written successfully."

# ---------------------------------------------------------------------------
# 5. Start Redis via Docker Compose
# ---------------------------------------------------------------------------
echo "[INFO] Starting Redis container ..."
docker compose --env-file "${ENV_FILE}" -f "${SCRIPT_DIR}/docker-compose.yml" up -d --build

echo ""
echo "[OK] Redis is running."
echo "     Host     : ${REDIS_HOST:-localhost}"
echo "     Port     : ${REDIS_PORT:-6379}"
echo "     Username : ${REDIS_USERNAME}"
echo ""
echo "To stop:   docker compose -f ${SCRIPT_DIR}/docker-compose.yml down"
echo "To logs:   docker compose -f ${SCRIPT_DIR}/docker-compose.yml logs -f"
